# Etapa de build
FROM node:20 AS build
WORKDIR /esracionamiento-frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de producción con nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
