# Generated by Django 5.2.2 on 2025-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Fiat', 'Fiat'), ('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Otro', 'Otro')], max_length=20)),
                ('color', models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Plateado', 'Plateado'), ('Otro', 'Otro')], max_length=20)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
