# Generated by Django 5.2.2 on 2025-08-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['patente']},
        ),
        migrations.RemoveField(
            model_name='auto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='fecha_salida',
        ),
        migrations.CreateModel(
            name='RegistroEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='parking.auto')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
